//Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
//--------------------------------------------------------------------------------
//Tool Version: Vivado v.2022.2 (lin64) Build 3671981 Fri Oct 14 04:59:54 MDT 2022
//Date        : Tue Oct 31 17:37:06 2023
//Host        : gusion running 64-bit Debian GNU/Linux 12 (bookworm)
//Command     : generate_target udl_axi_wrapper.bd
//Design      : udl_axi_wrapper
//Purpose     : IP block netlist
//--------------------------------------------------------------------------------
`timescale 1 ps / 1 ps

module udl_axi_wrapper
   (BUS_RSTB,
    MAXI_CLK,
    POR_RSTB,
    POR_RSTB_SYNC_REFCLK,
    REF_CLK,
    SYS_RSTB,
    SYS_RSTB_SYNC_REFCLK,
    SYS_RSTB_SYNC_USERCLK1,
    SYS_RSTB_SYNC_USERCLK2,
    TRCH_UART_RX,
    TRCH_UART_TX,
    UDL_AXIM_ARADDR,
    UDL_AXIM_ARBURST,
    UDL_AXIM_ARCACHE,
    UDL_AXIM_ARID,
    UDL_AXIM_ARLEN,
    UDL_AXIM_ARLOCK,
    UDL_AXIM_ARPROT,
    UDL_AXIM_ARQOS,
    UDL_AXIM_ARREADY,
    UDL_AXIM_ARSIZE,
    UDL_AXIM_ARVALID,
    UDL_AXIM_AWADDR,
    UDL_AXIM_AWBURST,
    UDL_AXIM_AWCACHE,
    UDL_AXIM_AWID,
    UDL_AXIM_AWLEN,
    UDL_AXIM_AWLOCK,
    UDL_AXIM_AWPROT,
    UDL_AXIM_AWQOS,
    UDL_AXIM_AWREADY,
    UDL_AXIM_AWSIZE,
    UDL_AXIM_AWVALID,
    UDL_AXIM_BID,
    UDL_AXIM_BREADY,
    UDL_AXIM_BRESP,
    UDL_AXIM_BVALID,
    UDL_AXIM_RDATA,
    UDL_AXIM_RID,
    UDL_AXIM_RLAST,
    UDL_AXIM_RREADY,
    UDL_AXIM_RRESP,
    UDL_AXIM_RVALID,
    UDL_AXIM_WDATA,
    UDL_AXIM_WLAST,
    UDL_AXIM_WREADY,
    UDL_AXIM_WSTRB,
    UDL_AXIM_WVALID,
    UDL_AXIS_ARADDR,
    UDL_AXIS_ARBURST,
    UDL_AXIS_ARCACHE,
    UDL_AXIS_ARID,
    UDL_AXIS_ARLEN,
    UDL_AXIS_ARLOCK,
    UDL_AXIS_ARPROT,
    UDL_AXIS_ARQOS,
    UDL_AXIS_ARREADY,
    UDL_AXIS_ARREGION,
    UDL_AXIS_ARSIZE,
    UDL_AXIS_ARVALID,
    UDL_AXIS_AWADDR,
    UDL_AXIS_AWBURST,
    UDL_AXIS_AWCACHE,
    UDL_AXIS_AWID,
    UDL_AXIS_AWLEN,
    UDL_AXIS_AWLOCK,
    UDL_AXIS_AWPROT,
    UDL_AXIS_AWQOS,
    UDL_AXIS_AWREADY,
    UDL_AXIS_AWREGION,
    UDL_AXIS_AWSIZE,
    UDL_AXIS_AWVALID,
    UDL_AXIS_BID,
    UDL_AXIS_BREADY,
    UDL_AXIS_BRESP,
    UDL_AXIS_BVALID,
    UDL_AXIS_RDATA,
    UDL_AXIS_RID,
    UDL_AXIS_RLAST,
    UDL_AXIS_RREADY,
    UDL_AXIS_RRESP,
    UDL_AXIS_RVALID,
    UDL_AXIS_WDATA,
    UDL_AXIS_WLAST,
    UDL_AXIS_WREADY,
    UDL_AXIS_WSTRB,
    UDL_AXIS_WVALID,
    UDL_INTISR,
    UIO1,
    UIO2,
    UIO3,
    USER_CLK1,
    USER_CLK2,
    WDOG_OUT);
  input BUS_RSTB;
  input MAXI_CLK;
  input POR_RSTB;
  input POR_RSTB_SYNC_REFCLK;
  input REF_CLK;
  input SYS_RSTB;
  input SYS_RSTB_SYNC_REFCLK;
  input SYS_RSTB_SYNC_USERCLK1;
  input SYS_RSTB_SYNC_USERCLK2;
  inout TRCH_UART_RX;
  inout TRCH_UART_TX;
  output [0:0]UDL_AXIM_ARADDR;
  output [1:0]UDL_AXIM_ARBURST;
  output [3:0]UDL_AXIM_ARCACHE;
  output [2:0]UDL_AXIM_ARID;
  output [7:0]UDL_AXIM_ARLEN;
  output [0:0]UDL_AXIM_ARLOCK;
  output [2:0]UDL_AXIM_ARPROT;
  output [3:0]UDL_AXIM_ARQOS;
  input UDL_AXIM_ARREADY;
  output [2:0]UDL_AXIM_ARSIZE;
  output [0:0]UDL_AXIM_ARVALID;
  output [31:0]UDL_AXIM_AWADDR;
  output [1:0]UDL_AXIM_AWBURST;
  output [3:0]UDL_AXIM_AWCACHE;
  output [1:0]UDL_AXIM_AWID;
  output [7:0]UDL_AXIM_AWLEN;
  output [0:0]UDL_AXIM_AWLOCK;
  output [2:0]UDL_AXIM_AWPROT;
  output [3:0]UDL_AXIM_AWQOS;
  input UDL_AXIM_AWREADY;
  output [2:0]UDL_AXIM_AWSIZE;
  output [0:0]UDL_AXIM_AWVALID;
  input [2:0]UDL_AXIM_BID;
  output [0:0]UDL_AXIM_BREADY;
  input [1:0]UDL_AXIM_BRESP;
  input UDL_AXIM_BVALID;
  input [31:0]UDL_AXIM_RDATA;
  input [2:0]UDL_AXIM_RID;
  input UDL_AXIM_RLAST;
  output [0:0]UDL_AXIM_RREADY;
  input [1:0]UDL_AXIM_RRESP;
  input UDL_AXIM_RVALID;
  output [31:0]UDL_AXIM_WDATA;
  output [0:0]UDL_AXIM_WLAST;
  input UDL_AXIM_WREADY;
  output [3:0]UDL_AXIM_WSTRB;
  output [0:0]UDL_AXIM_WVALID;
  input [31:0]UDL_AXIS_ARADDR;
  input [1:0]UDL_AXIS_ARBURST;
  input [3:0]UDL_AXIS_ARCACHE;
  input [2:0]UDL_AXIS_ARID;
  input [7:0]UDL_AXIS_ARLEN;
  input UDL_AXIS_ARLOCK;
  input [2:0]UDL_AXIS_ARPROT;
  input [3:0]UDL_AXIS_ARQOS;
  output [0:0]UDL_AXIS_ARREADY;
  input [3:0]UDL_AXIS_ARREGION;
  input [2:0]UDL_AXIS_ARSIZE;
  input UDL_AXIS_ARVALID;
  input [31:0]UDL_AXIS_AWADDR;
  input [1:0]UDL_AXIS_AWBURST;
  input [3:0]UDL_AXIS_AWCACHE;
  input [2:0]UDL_AXIS_AWID;
  input [7:0]UDL_AXIS_AWLEN;
  input UDL_AXIS_AWLOCK;
  input [2:0]UDL_AXIS_AWPROT;
  input [3:0]UDL_AXIS_AWQOS;
  output [0:0]UDL_AXIS_AWREADY;
  input [3:0]UDL_AXIS_AWREGION;
  input [2:0]UDL_AXIS_AWSIZE;
  input UDL_AXIS_AWVALID;
  output [2:0]UDL_AXIS_BID;
  input UDL_AXIS_BREADY;
  output [1:0]UDL_AXIS_BRESP;
  output [0:0]UDL_AXIS_BVALID;
  output [31:0]UDL_AXIS_RDATA;
  output [2:0]UDL_AXIS_RID;
  output [0:0]UDL_AXIS_RLAST;
  input UDL_AXIS_RREADY;
  output [1:0]UDL_AXIS_RRESP;
  output [0:0]UDL_AXIS_RVALID;
  input [31:0]UDL_AXIS_WDATA;
  input UDL_AXIS_WLAST;
  output [0:0]UDL_AXIS_WREADY;
  input [3:0]UDL_AXIS_WSTRB;
  input UDL_AXIS_WVALID;
  output [15:0]UDL_INTISR;
  inout [15:0]UIO1;
  inout [15:0]UIO2;
  inout [2:0]UIO3;
  input USER_CLK1;
  input USER_CLK2;
  inout WDOG_OUT;

  wire BUS_RSTB;
  wire MAXI_CLK;
  wire POR_RSTB;
  wire POR_RSTB_SYNC_REFCLK;
  wire REF_CLK;
  wire SYS_RSTB;
  wire SYS_RSTB_SYNC_REFCLK;
  wire SYS_RSTB_SYNC_USERCLK1;
  wire SYS_RSTB_SYNC_USERCLK2;
  wire TRCH_UART_RX;
  wire TRCH_UART_TX;
  wire [0:0]UDL_AXIM_ARADDR;
  wire [1:0]UDL_AXIM_ARBURST;
  wire [3:0]UDL_AXIM_ARCACHE;
  wire [2:0]UDL_AXIM_ARID;
  wire [7:0]UDL_AXIM_ARLEN;
  wire [0:0]UDL_AXIM_ARLOCK;
  wire [2:0]UDL_AXIM_ARPROT;
  wire [3:0]UDL_AXIM_ARQOS;
  wire UDL_AXIM_ARREADY;
  wire [2:0]UDL_AXIM_ARSIZE;
  wire [0:0]UDL_AXIM_ARVALID;
  wire [31:0]UDL_AXIM_AWADDR;
  wire [1:0]UDL_AXIM_AWBURST;
  wire [3:0]UDL_AXIM_AWCACHE;
  wire [1:0]UDL_AXIM_AWID;
  wire [7:0]UDL_AXIM_AWLEN;
  wire [0:0]UDL_AXIM_AWLOCK;
  wire [2:0]UDL_AXIM_AWPROT;
  wire [3:0]UDL_AXIM_AWQOS;
  wire UDL_AXIM_AWREADY;
  wire [2:0]UDL_AXIM_AWSIZE;
  wire [0:0]UDL_AXIM_AWVALID;
  wire [2:0]UDL_AXIM_BID;
  wire [0:0]UDL_AXIM_BREADY;
  wire [1:0]UDL_AXIM_BRESP;
  wire UDL_AXIM_BVALID;
  wire [31:0]UDL_AXIM_RDATA;
  wire [2:0]UDL_AXIM_RID;
  wire UDL_AXIM_RLAST;
  wire [0:0]UDL_AXIM_RREADY;
  wire [1:0]UDL_AXIM_RRESP;
  wire UDL_AXIM_RVALID;
  wire [31:0]UDL_AXIM_WDATA;
  wire [0:0]UDL_AXIM_WLAST;
  wire UDL_AXIM_WREADY;
  wire [3:0]UDL_AXIM_WSTRB;
  wire [0:0]UDL_AXIM_WVALID;
  wire [31:0]UDL_AXIS_ARADDR;
  wire [1:0]UDL_AXIS_ARBURST;
  wire [3:0]UDL_AXIS_ARCACHE;
  wire [2:0]UDL_AXIS_ARID;
  wire [7:0]UDL_AXIS_ARLEN;
  wire UDL_AXIS_ARLOCK;
  wire [2:0]UDL_AXIS_ARPROT;
  wire [3:0]UDL_AXIS_ARQOS;
  wire [0:0]UDL_AXIS_ARREADY;
  wire [3:0]UDL_AXIS_ARREGION;
  wire [2:0]UDL_AXIS_ARSIZE;
  wire UDL_AXIS_ARVALID;
  wire [31:0]UDL_AXIS_AWADDR;
  wire [1:0]UDL_AXIS_AWBURST;
  wire [3:0]UDL_AXIS_AWCACHE;
  wire [2:0]UDL_AXIS_AWID;
  wire [7:0]UDL_AXIS_AWLEN;
  wire UDL_AXIS_AWLOCK;
  wire [2:0]UDL_AXIS_AWPROT;
  wire [3:0]UDL_AXIS_AWQOS;
  wire [0:0]UDL_AXIS_AWREADY;
  wire [3:0]UDL_AXIS_AWREGION;
  wire [2:0]UDL_AXIS_AWSIZE;
  wire UDL_AXIS_AWVALID;
  wire [2:0]UDL_AXIS_BID;
  wire UDL_AXIS_BREADY;
  wire [1:0]UDL_AXIS_BRESP;
  wire [0:0]UDL_AXIS_BVALID;
  wire [31:0]UDL_AXIS_RDATA;
  wire [2:0]UDL_AXIS_RID;
  wire [0:0]UDL_AXIS_RLAST;
  wire UDL_AXIS_RREADY;
  wire [1:0]UDL_AXIS_RRESP;
  wire [0:0]UDL_AXIS_RVALID;
  wire [31:0]UDL_AXIS_WDATA;
  wire UDL_AXIS_WLAST;
  wire [0:0]UDL_AXIS_WREADY;
  wire [3:0]UDL_AXIS_WSTRB;
  wire UDL_AXIS_WVALID;
  wire [15:0]UDL_INTISR;
  wire [15:0]UIO1;
  wire [15:0]UIO2;
  wire [2:0]UIO3;
  wire USER_CLK1;
  wire USER_CLK2;
  wire WDOG_OUT;

  udl_axi udl_axi_i
       (.BUS_RSTB(BUS_RSTB),
        .MAXI_CLK(MAXI_CLK),
        .POR_RSTB(POR_RSTB),
        .POR_RSTB_SYNC_REFCLK(POR_RSTB_SYNC_REFCLK),
        .REF_CLK(REF_CLK),
        .SYS_RSTB(SYS_RSTB),
        .SYS_RSTB_SYNC_REFCLK(SYS_RSTB_SYNC_REFCLK),
        .SYS_RSTB_SYNC_USERCLK1(SYS_RSTB_SYNC_USERCLK1),
        .SYS_RSTB_SYNC_USERCLK2(SYS_RSTB_SYNC_USERCLK2),
        .TRCH_UART_RX(TRCH_UART_RX),
        .TRCH_UART_TX(TRCH_UART_TX),
        .UDL_AXIM_ARADDR(UDL_AXIM_ARADDR),
        .UDL_AXIM_ARBURST(UDL_AXIM_ARBURST),
        .UDL_AXIM_ARCACHE(UDL_AXIM_ARCACHE),
        .UDL_AXIM_ARID(UDL_AXIM_ARID),
        .UDL_AXIM_ARLEN(UDL_AXIM_ARLEN),
        .UDL_AXIM_ARLOCK(UDL_AXIM_ARLOCK),
        .UDL_AXIM_ARPROT(UDL_AXIM_ARPROT),
        .UDL_AXIM_ARQOS(UDL_AXIM_ARQOS),
        .UDL_AXIM_ARREADY(UDL_AXIM_ARREADY),
        .UDL_AXIM_ARSIZE(UDL_AXIM_ARSIZE),
        .UDL_AXIM_ARVALID(UDL_AXIM_ARVALID),
        .UDL_AXIM_AWADDR(UDL_AXIM_AWADDR),
        .UDL_AXIM_AWBURST(UDL_AXIM_AWBURST),
        .UDL_AXIM_AWCACHE(UDL_AXIM_AWCACHE),
        .UDL_AXIM_AWID(UDL_AXIM_AWID),
        .UDL_AXIM_AWLEN(UDL_AXIM_AWLEN),
        .UDL_AXIM_AWLOCK(UDL_AXIM_AWLOCK),
        .UDL_AXIM_AWPROT(UDL_AXIM_AWPROT),
        .UDL_AXIM_AWQOS(UDL_AXIM_AWQOS),
        .UDL_AXIM_AWREADY(UDL_AXIM_AWREADY),
        .UDL_AXIM_AWSIZE(UDL_AXIM_AWSIZE),
        .UDL_AXIM_AWVALID(UDL_AXIM_AWVALID),
        .UDL_AXIM_BID(UDL_AXIM_BID),
        .UDL_AXIM_BREADY(UDL_AXIM_BREADY),
        .UDL_AXIM_BRESP(UDL_AXIM_BRESP),
        .UDL_AXIM_BVALID(UDL_AXIM_BVALID),
        .UDL_AXIM_RDATA(UDL_AXIM_RDATA),
        .UDL_AXIM_RID(UDL_AXIM_RID),
        .UDL_AXIM_RLAST(UDL_AXIM_RLAST),
        .UDL_AXIM_RREADY(UDL_AXIM_RREADY),
        .UDL_AXIM_RRESP(UDL_AXIM_RRESP),
        .UDL_AXIM_RVALID(UDL_AXIM_RVALID),
        .UDL_AXIM_WDATA(UDL_AXIM_WDATA),
        .UDL_AXIM_WLAST(UDL_AXIM_WLAST),
        .UDL_AXIM_WREADY(UDL_AXIM_WREADY),
        .UDL_AXIM_WSTRB(UDL_AXIM_WSTRB),
        .UDL_AXIM_WVALID(UDL_AXIM_WVALID),
        .UDL_AXIS_ARADDR(UDL_AXIS_ARADDR),
        .UDL_AXIS_ARBURST(UDL_AXIS_ARBURST),
        .UDL_AXIS_ARCACHE(UDL_AXIS_ARCACHE),
        .UDL_AXIS_ARID(UDL_AXIS_ARID),
        .UDL_AXIS_ARLEN(UDL_AXIS_ARLEN),
        .UDL_AXIS_ARLOCK(UDL_AXIS_ARLOCK),
        .UDL_AXIS_ARPROT(UDL_AXIS_ARPROT),
        .UDL_AXIS_ARQOS(UDL_AXIS_ARQOS),
        .UDL_AXIS_ARREADY(UDL_AXIS_ARREADY),
        .UDL_AXIS_ARREGION(UDL_AXIS_ARREGION),
        .UDL_AXIS_ARSIZE(UDL_AXIS_ARSIZE),
        .UDL_AXIS_ARVALID(UDL_AXIS_ARVALID),
        .UDL_AXIS_AWADDR(UDL_AXIS_AWADDR),
        .UDL_AXIS_AWBURST(UDL_AXIS_AWBURST),
        .UDL_AXIS_AWCACHE(UDL_AXIS_AWCACHE),
        .UDL_AXIS_AWID(UDL_AXIS_AWID),
        .UDL_AXIS_AWLEN(UDL_AXIS_AWLEN),
        .UDL_AXIS_AWLOCK(UDL_AXIS_AWLOCK),
        .UDL_AXIS_AWPROT(UDL_AXIS_AWPROT),
        .UDL_AXIS_AWQOS(UDL_AXIS_AWQOS),
        .UDL_AXIS_AWREADY(UDL_AXIS_AWREADY),
        .UDL_AXIS_AWREGION(UDL_AXIS_AWREGION),
        .UDL_AXIS_AWSIZE(UDL_AXIS_AWSIZE),
        .UDL_AXIS_AWVALID(UDL_AXIS_AWVALID),
        .UDL_AXIS_BID(UDL_AXIS_BID),
        .UDL_AXIS_BREADY(UDL_AXIS_BREADY),
        .UDL_AXIS_BRESP(UDL_AXIS_BRESP),
        .UDL_AXIS_BVALID(UDL_AXIS_BVALID),
        .UDL_AXIS_RDATA(UDL_AXIS_RDATA),
        .UDL_AXIS_RID(UDL_AXIS_RID),
        .UDL_AXIS_RLAST(UDL_AXIS_RLAST),
        .UDL_AXIS_RREADY(UDL_AXIS_RREADY),
        .UDL_AXIS_RRESP(UDL_AXIS_RRESP),
        .UDL_AXIS_RVALID(UDL_AXIS_RVALID),
        .UDL_AXIS_WDATA(UDL_AXIS_WDATA),
        .UDL_AXIS_WLAST(UDL_AXIS_WLAST),
        .UDL_AXIS_WREADY(UDL_AXIS_WREADY),
        .UDL_AXIS_WSTRB(UDL_AXIS_WSTRB),
        .UDL_AXIS_WVALID(UDL_AXIS_WVALID),
        .UDL_INTISR(UDL_INTISR),
        .UIO1(UIO1),
        .UIO2(UIO2),
        .UIO3(UIO3),
        .USER_CLK1(USER_CLK1),
        .USER_CLK2(USER_CLK2),
        .WDOG_OUT(WDOG_OUT));
endmodule
